version: '2'
services:
    default:
        hostname: ss0
        domainname: javaws.com
        container_name: ss0
        tty: false
        image: shadowsocks:busybox
        network_mode: bridge
        ports: 
            - 443
        volumes:
            - ./tmp/config.json:/config.json
        restart: always
        command: ssserver

    public:
        hostname: ss1
        domainname: javaws.com
        container_name: ss1
        tty: false
        image: shadowsocks:busybox
        network_mode: bridge
        ports:
            - 443
        volumes:
            - ./tmp/public.json:/config.json
        restart: always
        command: ssserver
